### ISSUE TITLE
poll.c on windows

### ISSUE THREAD

**Issue by dsisnero** [Asmod4n/mruby-poll#4]
I tried to get mruby-websocket to compile under windows msys2-rubyinstaller but windows doesn't have poll.h .  Can we use libressl solutions for poll
https://github.com/libressl-portable/portable/blob/master/include/compat/poll.h

**Comment by Asmod4n** [comment]
Hello,

feel free to send a pull request.
Have you tried to run it in a wsl environment?

**Comment by Asmod4n** [comment]
Won't add windows functionality, if you need it please send a working PR.
